# Ressources

## Documents

Il existe de nombreux documents consacrés à R, y compris francophones. 

On notera notamment :

- *R et espace*, manuel d’initiation à la programmation avec R appliqué à l’analyse de l’information géographique, librement téléchargeable en ligne : https://framabook.org/r-et-espace/
- le document *Introduction à R*, orienté débutants et utilisateurs en SHS, également téléchargeable librement : https://alea.fr.eu.org/pages/intro-R

## Obtenir de l'aide

Outre l'aide intégrée au logiciel, il existe de nombreuses ressources en ligne, forums, listes de discussions, pour poser ses questions et échanger avec des utilisateurs de R.

Parmi les ressources francophones, on notera notamment :

- le forum dédié du CIRAD : http://forums.cirad.fr/logiciel-R/
- la liste semin-r : https://listes.mnhn.fr/wws/subscribe/semin-r
- la liste R-soc : https://groupes.renater.fr/sympa/subscribe/r-soc

Pour les anglophones, la partie dédiée à R du site *StackOverflow* contient un très grand nombre de questions et les réponses associées : https://stackoverflow.com/questions/tagged/r