project:
  type: book
  output-dir: _book
  lib-dir: lib
  resources: resources

execute:
  freeze: auto

lang: fr

book:
  title: "Introduction à R et au tidyverse"
  author: "Julien Barnier"
  date: today
  language: fr
  output-file: introduction_au_tidyverse
  downloads: [epub, pdf]
  doi: 10.5281/zenodo.6382598
  url: https://juba.github.io/tidyverse/
  repo-url: https://github.com/juba/tidyverse/
  repo-actions: [edit]
  search: true
  reader-mode: true
  sidebar:
    style: "docked"
    collapse-level: 1
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - 01-presentation.qmd
    - part: "Introduction à R"
      chapters:
        - 02-prise_en_main.qmd
        - 03-premier_travail.qmd
        - 04-bivarie.qmd
        - 05-organiser.qmd
    - part: "Introduction au tidyverse"
      chapters:
        - 06-tidyverse.qmd
        - 07-import.qmd
        - 08-ggplot2.qmd
        - 09-recodages.qmd
        - 10-dplyr.qmd
        - 11-stringr.qmd
        - 12-tidyr.qmd
        - 13-rmarkdown.qmd
    - part: "Aller plus loin"
      chapters:
        - 14-fonctions.qmd
        - 15-dplyr-avance.qmd
        - 16-structures-donnees.qmd
        - 17-if-boucles.qmd
        - 18-purrr.qmd
        - 19-programmer-tidyverse.qmd
        - 20-debuggage-performance.qmd
        - 21-targets.qmd
  appendices:
    - 22-ressources.qmd

format:
  html:
    theme:
      light: css/tidyverse.scss
      dark: css/dark.scss
    highlight: kate
    css: css/fonts.css
    dev: png
    default-image-extension: svg
    smooth-scroll: true
    include-after-body:
      text: |
        <script src="js/tidyverse.js"></script>
  pdf:
    documentclass: scrreport
    prefer-html: true
    default-image-extension: pdf
  epub:
    stylesheet: css/epub.css
    prefer-html: true
    default-image-extension: svg
