on:
  workflow_dispatch:
  push:
    branches: [main]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install dev packages
        run: sudo apt-get install -y libcurl4-openssl-dev libgdal-dev pandoc

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "release"

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up TinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          cache-version: 2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
